import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import { getServerSession } from 'next-auth/next'
import { authOptions } from './api/auth/[...nextauth]/route'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

const session = await getServerSession(authOptions);
console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        {session && ( <NavBar/>) }
        {children}
        </body>
    </html>
  )
}
